"""Publication-style figure generation for the experiment suite.

The figures are finite-dimensional numerical demonstrations aligned with the
theorem statements.  They are intended for a paper supplement, not as a
substitute for the infinite-dimensional proofs.
"""

from __future__ import annotations

from dataclasses import dataclass
import os
from pathlib import Path
import tempfile
from typing import Iterable

_MPLCONFIGDIR = Path(os.environ.get("MPLCONFIGDIR", Path(tempfile.gettempdir()) / "leakage_emergence_mpl"))
_MPLCONFIGDIR.mkdir(parents=True, exist_ok=True)
os.environ.setdefault("MPLCONFIGDIR", str(_MPLCONFIGDIR))

import matplotlib

matplotlib.use("Agg", force=True)

import matplotlib.pyplot as plt
import numpy as np

from . import experiments
from .utils import ensure_dir, row_norms

BLUE = "#1F5AA6"
RED = "#B83232"
DARK = "#202124"

DEFAULT_FORMATS = ("png", "pdf")


@dataclass(frozen=True)
class FigureCaption:
    """Paper-facing metadata for a generated figure."""

    stem: str
    label: str
    caption: str
    supports: str
    width: str = r"0.82\linewidth"

    @property
    def pdf_filename(self) -> str:
        return f"{self.stem}.pdf"


FIGURE_CAPTIONS: tuple[FigureCaption, ...] = (
    FigureCaption(
        stem="01_component_norms",
        label="fig:leakage-norms",
        caption=(
            "Finite-dimensional illustration of leakage from the hidden sector to the "
            "observable sector. The upper panel shows the hidden component norm "
            r"$\|\psi_p(t)\|$, while the lower panel shows the observable component "
            r"norm $\|\psi_a(t)\|$ generated by a nonzero leakage block."
        ),
        supports=(
            "The first-order emergence theorem, by showing observable-sector growth "
            "from hidden initial data when the leakage block is active."
        ),
    ),
    FigureCaption(
        stem="02_first_order_emergence",
        label="fig:first-order-emergence",
        caption=(
            r"Comparison of the directly computed observable amplitude $\|\psi_a(t)\|$ "
            r"with the leading term $t\|A_{ap}\psi_0\|$ for a hidden initial state. "
            "Agreement at early times illustrates the finite-dimensional version of "
            r"$\psi_a(t)=tA_{ap}\psi_0+o(t)$."
        ),
        supports="The first-order emergence statement.",
    ),
    FigureCaption(
        stem="03_duhamel_agreement",
        label="fig:duhamel-agreement",
        caption=(
            "Direct observable-sector evolution compared with the Duhamel "
            "variation-of-constants reconstruction. The error panel reports the "
            "norm of the difference between the two finite-dimensional computations."
        ),
        supports="The integrated leakage identity.",
    ),
    FigureCaption(
        stem="04_threshold_crossing",
        label="fig:threshold-crossing",
        caption=(
            r"Thresholded observation for the awareness signal $\|\Pi\psi(t)\|$. "
            r"The horizontal line marks the threshold $\Theta$, and the vertical "
            r"line marks the interpolated first crossing time $t_\Theta$."
        ),
        supports="The thresholded-observation construction.",
    ),
    FigureCaption(
        stem="05_spectral_hiddenness",
        label="fig:spectral-hiddenness",
        caption=(
            "Hidden eigenmode example. A hidden eigenvector remains in the hidden "
            "sector under the flow, while the bar plot reports the hidden and "
            "observable content of eigenvectors in the finite-dimensional operator."
        ),
        supports="The spectral hiddenness criterion.",
    ),
    FigureCaption(
        stem="06_resolvent_leakage",
        label="fig:resolvent-leakage",
        caption=(
            r"Leakage-resolvent norm $\|Q(\lambda I-A)^{-1}P\|_2$ along a complex "
            r"line in the resolvent set. The invariant example has zero leakage "
            "norm, while the leaky example produces nonzero hidden-to-observable "
            "mixing through the resolvent."
        ),
        supports="The resolvent leakage criterion.",
    ),
    FigureCaption(
        stem="07_nonlinear_emergence",
        label="fig:nonlinear-leakage",
        caption=(
            "Nonlinear hiddenness preservation versus nonlinear leakage. The "
            "sector-preserving cubic example keeps the observable norm at zero, "
            "whereas the rotated hidden sector with the same elementwise cubic "
            "mechanism develops an observable component."
        ),
        supports="The nonlinear invariance and nonlinear emergence examples.",
    ),
    FigureCaption(
        stem="08_early_time_scaling",
        label="fig:early-time-scaling",
        caption=(
            r"Log--log early-time scaling of observable amplitude and aware-sector "
            r"energy. The fitted slopes show $\|\psi_a(t)\|=O(t)$ and "
            r"$E_a(t)=O(t^2)$ in this finite-dimensional leakage-active example."
        ),
        supports="The second-order energy emergence diagnostic.",
    ),
)


def configure_matplotlib_defaults() -> None:
    """Apply clean, journal-friendly matplotlib defaults."""

    plt.rcParams.update(
        {
            "figure.dpi": 140,
            "figure.facecolor": "white",
            "savefig.facecolor": "white",
            "savefig.edgecolor": "white",
            "savefig.dpi": 360,
            "axes.facecolor": "white",
            "axes.edgecolor": "#222222",
            "axes.linewidth": 0.9,
            "axes.grid": True,
            "axes.axisbelow": True,
            "axes.titlesize": 16,
            "axes.labelsize": 14,
            "axes.spines.top": False,
            "axes.spines.right": False,
            "xtick.labelsize": 12,
            "ytick.labelsize": 12,
            "legend.fontsize": 12,
            "legend.frameon": False,
            "lines.linewidth": 2.5,
            "font.size": 12,
            "mathtext.fontset": "dejavusans",
        }
    )


def _finish_axis(ax: plt.Axes) -> None:
    """Apply consistent axis styling after plotting."""

    ax.grid(True, alpha=0.28, linewidth=0.8)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.tick_params(direction="out", length=4.5, width=0.9)


def save_figure(
    fig: plt.Figure,
    output_dir: Path,
    stem: str,
    *,
    formats: Iterable[str] = DEFAULT_FORMATS,
) -> list[Path]:
    """Save a figure in requested formats and return all saved paths."""

    output = ensure_dir(output_dir)
    fig.tight_layout()
    paths: list[Path] = []
    for fmt in formats:
        suffix = fmt.lower().lstrip(".")
        path = output / f"{stem}.{suffix}"
        save_kwargs: dict[str, object] = {"bbox_inches": "tight", "facecolor": "white"}
        if suffix == "png":
            save_kwargs["dpi"] = 360
        fig.savefig(path, **save_kwargs)
        paths.append(path)
    plt.close(fig)
    return paths


def write_figure_captions(output_dir: str | Path) -> Path:
    """Write LaTeX figure captions and include blocks for generated figures."""

    output = ensure_dir(output_dir)
    path = output / "figure_captions.tex"
    lines = [
        r"% Auto-generated by leakage_emergence.plotting.generate_all_figures.",
        r"% These captions describe finite-dimensional numerical illustrations;",
        r"% they do not claim to prove the infinite-dimensional theorem statements.",
        "",
    ]
    for item in FIGURE_CAPTIONS:
        lines.extend(
            [
                rf"% {item.pdf_filename}",
                rf"% Supports: {item.supports}",
                r"\begin{figure}[t]",
                r"  \centering",
                rf"  \includegraphics[width={item.width}]{{figures/{item.pdf_filename}}}",
                rf"  \caption{{{item.caption} \emph{{Theorem support:}} {item.supports}}}",
                rf"  \label{{{item.label}}}",
                r"\end{figure}",
                "",
            ]
        )
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def plot_component_norms(result: dict[str, object], output_dir: Path) -> list[Path]:
    """Plot hidden and observable sector norms in stacked panels."""

    trajectory = result["trajectory"]
    t = trajectory.t
    hidden_norm = row_norms(trajectory.psi_p_coords)
    observable_norm = row_norms(trajectory.psi_a_coords)

    fig, axes = plt.subplots(2, 1, figsize=(6.2, 4.6), sharex=True)
    axes[0].plot(t, hidden_norm, color=BLUE, label=r"$\|\psi_p(t)\|$")
    axes[0].set_ylabel(r"$\|\psi_p(t)\|$")
    axes[0].legend(loc="best")
    axes[0].set_title("Leakage from hidden to observable sector")

    axes[1].plot(t, observable_norm, color=RED, label=r"$\|\psi_a(t)\|$")
    axes[1].set_xlabel(r"time $t$")
    axes[1].set_ylabel(r"$\|\psi_a(t)\|$")
    axes[1].legend(loc="best")

    for ax in axes:
        _finish_axis(ax)
    return save_figure(fig, output_dir, "01_component_norms")


def plot_first_order_emergence(result: dict[str, object], output_dir: Path) -> list[Path]:
    """Plot direct observable amplitude against the first-order prediction."""

    trajectory = result["trajectory"]
    prediction = result["derived"]["first_order_prediction"]
    t = trajectory.t
    actual = row_norms(trajectory.psi_a_coords)
    predicted = row_norms(prediction)

    fig, ax = plt.subplots(figsize=(6.2, 4.2))
    ax.plot(t, actual, color=RED, label=r"direct $\|\psi_a(t)\|$")
    ax.plot(t, predicted, "--", color=DARK, label=r"$t\|A_{ap}\psi_0\|$")
    ax.set_xlabel(r"time $t$")
    ax.set_ylabel(r"observable amplitude")
    ax.set_title("First-order observable emergence")
    ax.legend(loc="best")
    _finish_axis(ax)
    return save_figure(fig, output_dir, "02_first_order_emergence")


def plot_duhamel_agreement(result: dict[str, object], output_dir: Path) -> list[Path]:
    """Plot direct observable dynamics versus Duhamel reconstruction."""

    trajectory = result["trajectory"]
    reconstructed = result["derived"]["duhamel_reconstruction"]
    t = trajectory.t
    direct_norm = row_norms(trajectory.psi_a_coords)
    reconstruction_norm = row_norms(reconstructed)
    error_norm = row_norms(trajectory.psi_a_coords - reconstructed)

    fig, axes = plt.subplots(1, 2, figsize=(8.4, 4.0))
    axes[0].plot(t, direct_norm, color=RED, label=r"direct $\|\psi_a(t)\|$")
    axes[0].plot(t, reconstruction_norm, "--", color=BLUE, label="Duhamel reconstruction")
    axes[0].set_xlabel(r"time $t$")
    axes[0].set_ylabel(r"observable amplitude")
    axes[0].set_title("Duhamel identity")
    axes[0].legend(loc="best")

    axes[1].semilogy(t[1:], error_norm[1:] + 1e-18, color=DARK, label=r"absolute error")
    axes[1].set_xlabel(r"time $t$")
    axes[1].set_ylabel(r"$\|\psi_a-\psi_a^{\mathrm{Duhamel}}\|$")
    axes[1].set_title("Reconstruction error")
    axes[1].legend(loc="best")

    for ax in axes:
        _finish_axis(ax)
    return save_figure(fig, output_dir, "03_duhamel_agreement")


def plot_threshold_crossing(result: dict[str, object], output_dir: Path) -> list[Path]:
    """Plot norm-threshold observation and the first crossing time."""

    trajectory = result["trajectory"]
    y_norm = result["derived"]["observation_norms"]
    theta = float(result["parameters"]["threshold"])
    crossing = float(result["metrics"]["threshold_crossing"])

    fig, ax = plt.subplots(figsize=(6.2, 4.2))
    ax.plot(trajectory.t, y_norm, color=BLUE, label=r"$\|\Pi \psi(t)\|$")
    ax.axhline(theta, color=RED, linestyle="--", label=r"threshold $\Theta$")
    if np.isfinite(crossing):
        ax.axvline(crossing, color=DARK, linestyle=":", label=rf"$t_\Theta = {crossing:.2f}$")
    ax.set_xlabel(r"time $t$")
    ax.set_ylabel(r"observation norm")
    ax.set_title("Thresholded observation and first crossing time")
    ax.legend(loc="best")
    _finish_axis(ax)
    return save_figure(fig, output_dir, "04_threshold_crossing")


def plot_spectral_hiddenness(result: dict[str, object], output_dir: Path) -> list[Path]:
    """Plot hidden eigenmode observability and eigenvector sector content."""

    trajectory = result["trajectory"]
    classifications = result["derived"]["classifications"]
    hidden = np.array([record["hidden_norm"] for record in classifications], dtype=float)
    observable = np.array([record["observable_norm"] for record in classifications], dtype=float)
    labels = [str(record["kind"]) for record in classifications]
    x = np.arange(len(labels))

    fig, axes = plt.subplots(1, 2, figsize=(8.4, 4.0))
    axes[0].plot(trajectory.t, row_norms(trajectory.psi_a_coords), color=RED, label=r"$\|\psi_a(t)\|$")
    axes[0].set_xlabel(r"time $t$")
    axes[0].set_ylabel(r"observable amplitude")
    axes[0].set_title("Hidden eigenmode remains hidden")
    axes[0].legend(loc="best")

    axes[1].bar(x - 0.18, hidden, width=0.36, label=r"$\|Pv\|$", color=BLUE)
    axes[1].bar(x + 0.18, observable, width=0.36, label=r"$\|Qv\|$", color=RED)
    axes[1].set_xticks(x, labels, rotation=25, ha="right")
    axes[1].set_ylim(0.0, 1.05)
    axes[1].set_ylabel("normalized component norm")
    axes[1].set_title("Eigenvector sector content")
    axes[1].legend(loc="best")

    for ax in axes:
        _finish_axis(ax)
    return save_figure(fig, output_dir, "05_spectral_hiddenness")


def plot_resolvent_leakage(result: dict[str, object], output_dir: Path) -> list[Path]:
    """Plot leakage-resolvent norms for invariant and leaky examples."""

    lambdas = result["derived"]["lambda_values"]
    zero_norms = result["derived"]["zero_norms"]
    leaky_norms = result["derived"]["leaky_norms"]

    fig, ax = plt.subplots(figsize=(6.2, 4.2))
    ax.plot(np.real(lambdas), zero_norms, color=BLUE, label=r"$A_{ap}=0$")
    ax.plot(np.real(lambdas), leaky_norms, color=RED, label=r"$A_{ap}\neq 0$")
    ax.set_xlabel(r"$\mathrm{Re}\,\lambda$ with fixed $\mathrm{Im}\,\lambda$")
    ax.set_ylabel(r"$\|Q(\lambda I-A)^{-1}P\|_2$")
    ax.set_title("Resolvent leakage criterion")
    ax.legend(loc="best")
    _finish_axis(ax)
    return save_figure(fig, output_dir, "06_resolvent_leakage")


def plot_nonlinear_emergence(result: dict[str, object], output_dir: Path) -> list[Path]:
    """Plot nonlinear hiddenness preservation versus nonlinear leakage."""

    preserving = result["trajectory"]["preserving"]
    rotated = result["trajectory"]["rotated"]
    preserving_norm = row_norms(preserving.psi_a_coords)
    rotated_norm = row_norms(rotated.psi_a_coords)
    ymax = max(float(np.max(rotated_norm)), 1e-6)

    fig, ax = plt.subplots(figsize=(6.2, 4.2))
    ax.plot(
        preserving.t,
        preserving_norm,
        color=BLUE,
        label="hiddenness-preserving nonlinearity",
    )
    ax.plot(
        rotated.t,
        rotated_norm,
        color=RED,
        label="leak-inducing nonlinearity",
    )
    ax.set_xlim(0.0, float(rotated.t[-1]))
    ax.set_ylim(-0.04 * ymax, 1.12 * ymax)
    ax.set_xlabel(r"time $t$")
    ax.set_ylabel(r"$\|\psi_a(t)\|$")
    ax.set_title("Nonlinear preservation versus nonlinear leakage")
    ax.legend(loc="upper left")
    _finish_axis(ax)
    return save_figure(fig, output_dir, "07_nonlinear_emergence")


def plot_early_time_scaling(result: dict[str, object], output_dir: Path) -> list[Path]:
    """Plot early-time observable amplitude and energy on log-log axes."""

    t = result["trajectory"].t
    amplitude = result["derived"]["observable_norm"]
    energy = result["derived"]["E_a"]
    amplitude_slope = float(result["metrics"]["amplitude_loglog_slope"])
    energy_slope = float(result["metrics"]["energy_loglog_slope"])
    positive = t > 0.0
    t_pos = t[positive]
    amplitude_pos = amplitude[positive]
    energy_pos = energy[positive]

    fig, ax = plt.subplots(figsize=(6.2, 4.2))
    ax.loglog(
        t_pos,
        amplitude_pos,
        color=RED,
        label=rf"$\|\psi_a(t)\|$ (fit slope {amplitude_slope:.2f})",
    )
    ax.loglog(
        t_pos,
        energy_pos,
        color=BLUE,
        label=rf"$E_a(t)$ (fit slope {energy_slope:.2f})",
    )

    guide_t = np.array([t_pos[0], t_pos[-1]])
    ax.loglog(guide_t, amplitude_pos[0] * (guide_t / guide_t[0]), ":", color=RED, alpha=0.75)
    ax.loglog(guide_t, energy_pos[0] * (guide_t / guide_t[0]) ** 2, ":", color=BLUE, alpha=0.75)

    ax.set_xlabel(r"time $t$")
    ax.set_ylabel(r"amplitude and energy")
    ax.set_title("Early-time scaling of observable amplitude and energy")
    ax.legend(loc="best")
    _finish_axis(ax)
    return save_figure(fig, output_dir, "08_early_time_scaling")


def generate_all_figures(output_dir: str | Path = "figures") -> list[Path]:
    """Generate all theorem-supporting supplement figures."""

    configure_matplotlib_defaults()
    output = ensure_dir(output_dir)
    all_results = experiments.run_all_experiments()
    paths: list[Path] = []
    paths.extend(plot_component_norms(all_results["first_order_emergence"], output))
    paths.extend(plot_first_order_emergence(all_results["first_order_emergence"], output))
    paths.extend(plot_duhamel_agreement(all_results["duhamel_identity"], output))
    paths.extend(plot_threshold_crossing(all_results["threshold_detection"], output))
    paths.extend(plot_spectral_hiddenness(all_results["hidden_eigenmode"], output))
    paths.extend(plot_resolvent_leakage(all_results["resolvent_leakage"], output))
    paths.extend(plot_nonlinear_emergence(all_results["nonlinear_emergence"], output))
    paths.extend(plot_early_time_scaling(all_results["early_time_scaling"], output))
    paths.append(write_figure_captions(output))
    return paths
